######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 22 11:32:12 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

include(Qtilities.pri)
